sudo: false

language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk7
  - oraclejdk8

before_script:
  - cd shine

sbt_args: -XX:+CMSClassUnloadingEnabled

script:
- sbt -Dconfig.file=conf/travis.conf test

